site_name: mars.ninja
site_url: https://mars.ninja
use_directory_urls: true

nav:
  - blog/index.md
  - Blog:
    - blog/index.md
  - About: about.md

theme:
  name: material
  logo: assets/ninjaavatar.png
  favicon: assets/ninjaavatar.png
  font:
    text: Nunito
    code: Fira Code
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      pygments_style: autumn
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["."]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - tables
  - toc:
      permalink: "#"

extra_css:
  - extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername

copyright: Copyright &copy; 2025 Jason Mars

extra_javascript:
  - https://cdn.jsdelivr.net/pyodide/v0.27.0/full/pyodide.js
  - https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.52.2/min/vs/loader.min.js
  - js/jac.monarch.js
  - js/run-code.js

plugins:
  - search
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      post_date_format: medium
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      post_readtime: true
      post_readtime_words_per_minute: 200
      archive: true
      archive_name: Archive
      archive_date_format: MMMM yyyy
      archive_url_date_format: yyyy/MM
      archive_url_format: "archive/{date}"
      categories: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
      categories_allowed:
        - Jac Programming
        - Tutorials
        - AI & ML
        - Web Development
        - Object-Spatial Programming
      authors: true
      authors_file: "{blog}/.authors.yml"
      pagination: true
      pagination_per_page: 10
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      draft: true
      draft_on_serve: true
      draft_if_future_date: false

hooks:
  - scripts/handle_jac_compile_data.py
