authors:
  mars:
    name: Jason Mars
    description: Creator of Jac, Enjoyer of beautiful tech, The ninja professor.
    avatar: ../assets/ninjaavatar.png
  udith:
    name: Udith Ishanka
    description: Jac developer and contributor.
    avatar: ../assets/image.png
