name: Build and Deploy Mars Blog

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-mars-blog:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up QEMU for multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx for multi-architecture builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.2.0
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::776241927220:role/GitHubActionsSharedECRRole
          role-session-name: GitHubActions
          audience: sts.amazonaws.com

      - name: Debug AWS Credentials
        run: |
          aws sts get-caller-identity

      - name: Debug OIDC Token
        run: |
          echo "OIDC_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com"
      
      # Login to AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Extract tag name from GitHub ref
      - name: Get tag name
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            # Push to main - use commit SHA short version
            TAG="main-${GITHUB_SHA::7}"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Manual dispatch - use timestamp
            TAG="manual-$(date +%Y%m%d-%H%M%S)"
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            # Release event - clean tag name
            TAG_NAME=${GITHUB_REF#refs/tags/}
            
            # Remove 'v' prefix if present: v1.2.3 -> 1.2.3
            if [[ $TAG_NAME =~ ^v(.+)$ ]]; then
              TAG="${BASH_REMATCH[1]}"
            else
              TAG="$TAG_NAME"
            fi
          else
            # Fallback
            TAG="latest"
          fi
          
          echo "Tag: $TAG"
          echo "Event: ${{ github.event_name }}"
          echo "Original Tag Name: ${TAG_NAME:-N/A}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # Build and push Docker image
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 776241927220.dkr.ecr.us-east-2.amazonaws.com
          ECR_REPOSITORY: mars-blog
          IMAGE_TAG: ${{ steps.tag.outputs.tag }}
        run: |
          echo "Building and pushing to: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          
          # Build and push multi-architecture image
          docker buildx build \
            --platform linux/amd64 \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            --push \
            .

  summary:
    needs: [deploy-mars-blog]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Build and Push Summary
        run: |
          echo "## Mars Blog Build and Push Summary" >> $GITHUB_STEP_SUMMARY
          echo "### Blog Website" >> $GITHUB_STEP_SUMMARY
          echo "- **Image Tag**: ${{ needs.deploy-mars-blog.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **ECR Repository**: 776241927220.dkr.ecr.us-east-2.amazonaws.com/mars-blog" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ needs.deploy-mars-blog.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note**: Deployment will be handled automatically by Flux in the infrastructure repository." >> $GITHUB_STEP_SUMMARY
